# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_gui.ui'
#
# Created: Sun Jul  5 15:58:17 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(478, 477)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/gui-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_6 = QtGui.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_6.addWidget(self.label_6)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem1)
        self.toolButton_3 = QtGui.QToolButton(self.tab_1)
        self.toolButton_3.setStyleSheet(_fromUtf8("QToolButton{\n"
"border:none;\n"
"background:transparent;\n"
"}"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/hemoglobin-level.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon1)
        self.toolButton_3.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.verticalLayout_5.addWidget(self.toolButton_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_8 = QtGui.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.spinBox_hgb_level = QtGui.QSpinBox(self.tab_1)
        self.spinBox_hgb_level.setMaximum(999999999)
        self.spinBox_hgb_level.setObjectName(_fromUtf8("spinBox_hgb_level"))
        self.horizontalLayout.addWidget(self.spinBox_hgb_level)
        self.comboBox_HgB_units = QtGui.QComboBox(self.tab_1)
        self.comboBox_HgB_units.setObjectName(_fromUtf8("comboBox_HgB_units"))
        self.comboBox_HgB_units.addItem(_fromUtf8(""))
        self.comboBox_HgB_units.addItem(_fromUtf8(""))
        self.comboBox_HgB_units.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_HgB_units)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem3)
        self.toolButton_2 = QtGui.QToolButton(self.tab_1)
        self.toolButton_2.setStyleSheet(_fromUtf8("QToolButton{\n"
"border:none;\n"
"background:transparent;\n"
"}"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/gender.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.verticalLayout_3.addWidget(self.toolButton_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_9 = QtGui.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.comboBox_age_group_tab1 = QtGui.QComboBox(self.tab_1)
        self.comboBox_age_group_tab1.setObjectName(_fromUtf8("comboBox_age_group_tab1"))
        self.comboBox_age_group_tab1.addItem(_fromUtf8(""))
        self.comboBox_age_group_tab1.addItem(_fromUtf8(""))
        self.comboBox_age_group_tab1.addItem(_fromUtf8(""))
        self.comboBox_age_group_tab1.addItem(_fromUtf8(""))
        self.comboBox_age_group_tab1.addItem(_fromUtf8(""))
        self.comboBox_age_group_tab1.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBox_age_group_tab1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.line = QtGui.QFrame(self.tab_1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_6.addWidget(self.line)
        self.label_7 = QtGui.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_6.addWidget(self.label_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.toolButton_6 = QtGui.QToolButton(self.tab_1)
        self.toolButton_6.setStyleSheet(_fromUtf8("QToolButton{\n"
"border:none;\n"
"background:transparent;\n"
"}"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/diagnosis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon3)
        self.toolButton_6.setIconSize(QtCore.QSize(27, 27))
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.horizontalLayout_3.addWidget(self.toolButton_6)
        self.label_25 = QtGui.QLabel(self.tab_1)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_3.addWidget(self.label_25)
        self.lineEdit_diagnosis = QtGui.QLineEdit(self.tab_1)
        self.lineEdit_diagnosis.setObjectName(_fromUtf8("lineEdit_diagnosis"))
        self.horizontalLayout_3.addWidget(self.lineEdit_diagnosis)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.toolButton_anemia_icon = QtGui.QToolButton(self.tab_1)
        self.toolButton_anemia_icon.setStyleSheet(_fromUtf8("QToolButton{\n"
"border:none;\n"
"background:transparent;\n"
"}"))
        self.toolButton_anemia_icon.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/mild_anemia.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_anemia_icon.setIcon(icon4)
        self.toolButton_anemia_icon.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_anemia_icon.setObjectName(_fromUtf8("toolButton_anemia_icon"))
        self.horizontalLayout_6.addWidget(self.toolButton_anemia_icon)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.toolButton_5 = QtGui.QToolButton(self.tab_1)
        self.toolButton_5.setStyleSheet(_fromUtf8("QToolButton{\n"
"border:none;\n"
"background:transparent;\n"
"}"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/conversion.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon5)
        self.toolButton_5.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.horizontalLayout_4.addWidget(self.toolButton_5)
        self.label_24 = QtGui.QLabel(self.tab_1)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_4.addWidget(self.label_24)
        self.lineEdit_conversion = QtGui.QLineEdit(self.tab_1)
        self.lineEdit_conversion.setObjectName(_fromUtf8("lineEdit_conversion"))
        self.horizontalLayout_4.addWidget(self.lineEdit_conversion)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.toolButton_7 = QtGui.QToolButton(self.tab)
        self.toolButton_7.setStyleSheet(_fromUtf8("QToolButton{\n"
"border:none;\n"
"background:transparent;\n"
"}"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/symptoms.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon6)
        self.toolButton_7.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
        self.verticalLayout_4.addWidget(self.toolButton_7)
        self.comboBox_anemia_type_tab3 = QtGui.QComboBox(self.tab)
        self.comboBox_anemia_type_tab3.setObjectName(_fromUtf8("comboBox_anemia_type_tab3"))
        self.comboBox_anemia_type_tab3.addItem(_fromUtf8(""))
        self.comboBox_anemia_type_tab3.addItem(_fromUtf8(""))
        self.comboBox_anemia_type_tab3.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.comboBox_anemia_type_tab3)
        self.textEdit_anemia_symptoms = QtGui.QTextEdit(self.tab)
        self.textEdit_anemia_symptoms.setObjectName(_fromUtf8("textEdit_anemia_symptoms"))
        self.verticalLayout_4.addWidget(self.textEdit_anemia_symptoms)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_7.addWidget(self.label_2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_7.addItem(spacerItem5)
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_7.addWidget(self.label_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.toolButton_4 = QtGui.QToolButton(self.tab_3)
        self.toolButton_4.setStyleSheet(_fromUtf8("QToolButton{\n"
"border:none;\n"
"background:transparent;\n"
"}"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/food-amount.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon7)
        self.toolButton_4.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.horizontalLayout_10.addWidget(self.toolButton_4)
        self.spinBox_quantity_of_food = QtGui.QSpinBox(self.tab_3)
        self.spinBox_quantity_of_food.setMaximum(999999999)
        self.spinBox_quantity_of_food.setObjectName(_fromUtf8("spinBox_quantity_of_food"))
        self.horizontalLayout_10.addWidget(self.spinBox_quantity_of_food)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_9.addWidget(self.label)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.pushButton_expand_collapse_tree = QtGui.QPushButton(self.tab_3)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/expand.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_expand_collapse_tree.setIcon(icon8)
        self.pushButton_expand_collapse_tree.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_expand_collapse_tree.setObjectName(_fromUtf8("pushButton_expand_collapse_tree"))
        self.verticalLayout_7.addWidget(self.pushButton_expand_collapse_tree)
        self.label_3 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_7.addWidget(self.label_3)
        self.treeWidget = QtGui.QTreeWidget(self.tab_3)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidget.header().setCascadingSectionResizes(True)
        self.treeWidget.header().setDefaultSectionSize(0)
        self.treeWidget.header().setMinimumSectionSize(0)
        self.treeWidget.header().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.treeWidget)
        self.horizontalLayout_12.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem7)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem8)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_12.addWidget(self.label_5)
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setStyleSheet(_fromUtf8("QPushButton{\n"
"background: transparent;\n"
"border: none;\n"
"}"))
        self.pushButton_3.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/iib-logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon9)
        self.pushButton_3.setIconSize(QtCore.QSize(130, 60))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_12.addWidget(self.pushButton_3)
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_12.addWidget(self.label_11)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem9)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.pushButton_5 = QtGui.QPushButton(self.tab_2)
        self.pushButton_5.setStyleSheet(_fromUtf8("QPushButton{\n"
"background: transparent;\n"
"border: none;\n"
"}"))
        self.pushButton_5.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/email.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon10)
        self.pushButton_5.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem12)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_10.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_10.addWidget(self.label_14)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem13)
        self.horizontalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem14)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem15)
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_11.addWidget(self.label_15)
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setStyleSheet(_fromUtf8("QPushButton{\n"
"background: transparent;\n"
"border: none;\n"
"}"))
        self.pushButton_2.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/cc-license.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon11)
        self.pushButton_2.setIconSize(QtCore.QSize(88, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_11.addWidget(self.pushButton_2)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem16)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 478, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyAnemia", None))
        self.label_6.setText(_translate("MainWindow", "In this table, you can diagnose various stages of anemia based on the level of hemoglobin in the blood.", None))
        self.toolButton_3.setText(_translate("MainWindow", "...", None))
        self.label_8.setText(_translate("MainWindow", "Select hemoglobin level", None))
        self.spinBox_hgb_level.setToolTip(_translate("MainWindow", "Select hemoglobin level", None))
        self.comboBox_HgB_units.setToolTip(_translate("MainWindow", "Select units", None))
        self.comboBox_HgB_units.setItemText(0, _translate("MainWindow", "g/dl", None))
        self.comboBox_HgB_units.setItemText(1, _translate("MainWindow", "g/L", None))
        self.comboBox_HgB_units.setItemText(2, _translate("MainWindow", "mmol/L", None))
        self.toolButton_2.setToolTip(_translate("MainWindow", "Choose age and gender of the patient", None))
        self.toolButton_2.setText(_translate("MainWindow", "...", None))
        self.label_9.setToolTip(_translate("MainWindow", "Choose age and gender of the patient", None))
        self.label_9.setText(_translate("MainWindow", "Choose age and gender group", None))
        self.comboBox_age_group_tab1.setToolTip(_translate("MainWindow", "Choose age and gender of the patient", None))
        self.comboBox_age_group_tab1.setItemText(0, _translate("MainWindow", "Males > 15-years", None))
        self.comboBox_age_group_tab1.setItemText(1, _translate("MainWindow", "Females > 15-years", None))
        self.comboBox_age_group_tab1.setItemText(2, _translate("MainWindow", "Males < 15-years", None))
        self.comboBox_age_group_tab1.setItemText(3, _translate("MainWindow", "Females < 15-years", None))
        self.comboBox_age_group_tab1.setItemText(4, _translate("MainWindow", "Females pregnant", None))
        self.comboBox_age_group_tab1.setItemText(5, _translate("MainWindow", "Children < 8-years", None))
        self.label_7.setText(_translate("MainWindow", "Results:", None))
        self.toolButton_6.setToolTip(_translate("MainWindow", "Type of anemia based on patient\'s hemoglobin level", None))
        self.toolButton_6.setText(_translate("MainWindow", "...", None))
        self.label_25.setToolTip(_translate("MainWindow", "Type of anemia based on patient\'s hemoglobin level", None))
        self.label_25.setText(_translate("MainWindow", "Diagnosis", None))
        self.lineEdit_diagnosis.setToolTip(_translate("MainWindow", "Type of anemia based on patient\'s hemoglobin level", None))
        self.toolButton_5.setText(_translate("MainWindow", "...", None))
        self.label_24.setText(_translate("MainWindow", "Conversion", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Diagnosis of Anemia", None))
        self.toolButton_7.setText(_translate("MainWindow", "...", None))
        self.comboBox_anemia_type_tab3.setItemText(0, _translate("MainWindow", "Choose anemia type", None))
        self.comboBox_anemia_type_tab3.setItemText(1, _translate("MainWindow", "Mild anemia", None))
        self.comboBox_anemia_type_tab3.setItemText(2, _translate("MainWindow", "Severe anemia", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Symptoms of anemia", None))
        self.label_2.setText(_translate("MainWindow", "Thisi table takes quantity of food in grams and finds out how much iron is contained in it for every possible food category.", None))
        self.label_4.setText(_translate("MainWindow", "Please select the quantity of food:", None))
        self.toolButton_4.setToolTip(_translate("MainWindow", "Amount of food in grams", None))
        self.toolButton_4.setText(_translate("MainWindow", "...", None))
        self.spinBox_quantity_of_food.setToolTip(_translate("MainWindow", "Amount of food in grams", None))
        self.label.setText(_translate("MainWindow", "grams", None))
        self.pushButton_expand_collapse_tree.setText(_translate("MainWindow", "Expand Categories", None))
        self.label_3.setText(_translate("MainWindow", "List of foods high in iron:", None))
        self.treeWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p>Amount of iron contained in various eatables for the quantity of food chosen above</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "List of iron-rich foods", None))
        self.label_5.setText(_translate("MainWindow", "   Created by Afia Azam and Javieria Atiq at", None))
        self.label_11.setText(_translate("MainWindow", "CECOS University of IT & Emerging Sciences\n"
"Peshawar, Pakistan.", None))
        self.label_13.setText(_translate("MainWindow", "afia.azam.biologist@gmail.com", None))
        self.label_14.setText(_translate("MainWindow", "javieriaAtiq@gmail.com ", None))
        self.label_15.setText(_translate("MainWindow", "This work is licensed under a \n"
"Creative Commons\n"
"Attribution 4.0 International License.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "About", None))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

